const assert=require('node:assert/strict'),c=require('../assets/js/calculators-core-phase5.js'),near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`);
const C=[
['startupCost',{registration:1,equipment:2,inventory:3,marketing:4,deposit:5,operatingReserve:6,other:7},28],
['currentRatio',{currentAssets:100,currentLiabilities:50},2],['cashConversionCycle',{dio:45,dso:30,dpo:25},50],
['operatingExpenseRatio',{operatingExpenses:30,revenue:100},30],['variableCostRatio',{variableCosts:40,revenue:100},40],
['marginOfSafety',{sales:1000,breakEvenSales:700},300],['operatingLeverage',{contributionMargin:500,operatingProfit:200},2.5],
['revenueForecast',{currentRevenue:100,growthRate:10,periods:2},121],['profitGrowth',{previousProfit:200,currentProfit:250},25],
['expenseGrowth',{previousExpense:200,currentExpense:230},15],['gmv',{units:100,averageSellingPrice:50},5000],
['sellThrough',{unitsSold:60,unitsAvailable:100},60],['repeatPurchase',{repeatCustomers:20,totalCustomers:100},20],
['returnRate',{returned:5,total:100},5],['reorderPoint',{dailyDemand:20,leadTimeDays:10,safetyStock:100},300],
['leadVelocity',{previousLeads:200,currentLeads:250},25],['paybackPeriod',{cac:5000,monthlyRevenuePerCustomer:2000,grossMargin:50},5],
['marketingEfficiency',{totalRevenue:2000,marketingSpend:400},5],['marketingRoi',{marketingReturn:800,marketingCost:400},100],
['emailConversion',{conversions:25,deliveredEmails:1000},2.5],['billableHours',{workingDays:200,hoursPerDay:8,nonBillablePercent:25},1200],
['capacityUtilization',{productiveOutput:1200,availableCapacity:1600},75],['employeeCost',{salary:600,benefits:60,employerExpenses:30,otherCosts:10},700],
['salaryHourly',{annualSalary:120000,workingDays:200,hoursPerDay:8},75],['overheadRate',{overheadCosts:300,directLabourCost:600},50]];
for(const[name,input,expected]of C){near(c[name](input).primary,expected);for(const scale of[.75,.5]){const v=Object.fromEntries(Object.entries(input).map(([k,x])=>[k,x*scale]));const r=c[name](v);assert.ok(Number.isFinite(r.primary))}console.log('PASS',name,'3 normal cases')}
assert.equal(c.cashConversionCycle({dio:0,dso:0,dpo:20}).primary,-20);assert.equal(c.marginOfSafety({sales:100,breakEvenSales:100}).primary,0);assert.equal(c.revenueForecast({currentRevenue:100,growthRate:0,periods:0}).primary,100);assert.throws(()=>c.profitGrowth({previousProfit:0,currentProfit:10}));assert.throws(()=>c.profitGrowth({previousProfit:-10,currentProfit:10}));assert.equal(c.reorderPoint({dailyDemand:0,leadTimeDays:0,safetyStock:10}).primary,10);assert.equal(c.marketingRoi({marketingReturn:0,marketingCost:100}).primary,-100);assert.equal(c.employeeCost({salary:0,benefits:0,employerExpenses:0,otherCosts:0}).primary,0);
const bad=[['startupCost',{registration:-1,equipment:0,inventory:0,marketing:0,deposit:0,operatingReserve:0,other:0}],['currentRatio',{currentAssets:1,currentLiabilities:0}],['cashConversionCycle',{dio:-1,dso:1,dpo:1}],['operatingExpenseRatio',{operatingExpenses:1,revenue:0}],['variableCostRatio',{variableCosts:1,revenue:0}],['marginOfSafety',{sales:-1,breakEvenSales:0}],['operatingLeverage',{contributionMargin:1,operatingProfit:0}],['revenueForecast',{currentRevenue:1,growthRate:-100,periods:1}],['profitGrowth',{previousProfit:0,currentProfit:1}],['expenseGrowth',{previousExpense:0,currentExpense:1}],['gmv',{units:-1,averageSellingPrice:1}],['sellThrough',{unitsSold:2,unitsAvailable:1}],['repeatPurchase',{repeatCustomers:2,totalCustomers:1}],['returnRate',{returned:2,total:1}],['reorderPoint',{dailyDemand:-1,leadTimeDays:1,safetyStock:0}],['leadVelocity',{previousLeads:0,currentLeads:1}],['paybackPeriod',{cac:1,monthlyRevenuePerCustomer:1,grossMargin:0}],['marketingEfficiency',{totalRevenue:1,marketingSpend:0}],['marketingRoi',{marketingReturn:1,marketingCost:0}],['emailConversion',{conversions:2,deliveredEmails:1}],['billableHours',{workingDays:367,hoursPerDay:8,nonBillablePercent:0}],['capacityUtilization',{productiveOutput:2,availableCapacity:1}],['employeeCost',{salary:-1,benefits:0,employerExpenses:0,otherCosts:0}],['salaryHourly',{annualSalary:1,workingDays:0,hoursPerDay:8}],['overheadRate',{overheadCosts:1,directLabourCost:0}]];
for(const[name,input]of bad)assert.throws(()=>c[name](input));console.log('Phase 5: 75 normal checks, 8 boundary checks and 25 invalid checks passed.');
